export const products = [
  {
    id: 1,
    image: "erasure.jpg",
    title: "Erasure",
    author: "by Percival Everett",
    genre: "Children",
    price: 120000,
  },
  {
    id: 2,
    image: "harlem_shuffle.jpg",
    title: "Harlem Shuffle",
    author: "by Colson Whitehead",
    genre: "Children",
    price: 150000,
  },
  {
    id: 3,
    image: "native_nations.jpg",
    title: "Native Nations",
    author: "by Kathleen Duval",
    genre: "Children",
    price: 180000,
  },
  {
    id: 4,
    image: "this_motherless_land.jpg",
    title: "This Motherless Land",
    author: "by Nikki May",
    genre: "Children",
    price: 110000,
  },
  {
    id: 5,
    image: "erasure.jpg",
    title: "The Haunting",
    author: "by Shirley Jackson",
    genre: "Horror",
    price: 99000,
  },
  {
    id: 6,
    image: "harlem_shuffle.jpg",
    title: "It",
    author: "by Stephen King",
    genre: "Horror",
    price: 175000,
  },
  {
    id: 7,
    image: "native_nations.jpg",
    title: "Dracula",
    author: "by Bram Stoker",
    genre: "Horror",
    price: 130000,
  },
  {
    id: 8,
    image: "this_motherless_land.jpg",
    title: "Pet Sematary",
    author: "by Stephen King",
    genre: "Horror",
    price: 160000,
  },
];